name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-webapp:
    defaults:
      run:
        working-directory: webapp

    timeout-minutes: 10
    # We're running on ubuntu-latest, nothing special
    runs-on: ubuntu-latest
    steps:
      # As usual, we simply checkout the project
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 8.2.0

      - name: Install dependencies
        run: pnpm install

      - name: Build the project
        run: pnpm run build

      - name: Run lints
        run: pnpm run lint

      - name: Run checks
        run: pnpm run check

      - name: Run tests
        run: pnpm run test:unit
      
      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: webapp-build
          path: webapp/build

  deploy-webapp:
    needs: test-webapp
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v3
      #   with:
      #     repository: foryouandyourcustomers/the-hidden-threat-built
      #     ref: main

      - uses: actions/download-artifact@v2
        with:
          name: webapp-build
          path: webapp-build

      - name: Push to built repo
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'webapp-build'
          destination-github-username: 'foryouandyourcustomers'
          destination-repository-name: 'the-hidden-threat-built'
          user-email: m@tias.me
          target-branch: main

      - name: Trigger redeploy on render.com
        env:
          RENDER_DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_URL }}
        run: curl "$RENDER_DEPLOY_URL"
      
      # - name: GIT commit and push all changed files
      #   env: 
      #     CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
      #     CI_COMMIT_AUTHOR: Continuous Integration
      #   run: |
      #     git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
      #     git config --global user.email "username@users.noreply.github.com"
      #     git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
      #     git push
