name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 10
    # We're running on ubuntu-latest, nothing special
    runs-on: ubuntu-latest
    steps:
      # As usual, we simply checkout the project
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 8.2.0

      - name: Install dependencies
        run: pnpm install

      - name: Build the project
        run: pnpm run build

      - name: Run lints
        run: pnpm run lint

      # - name: Run checks
      #   run: pnpm run check

      - name: Run tests
        run: pnpm run test:unit
