name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-webapp:
    defaults:
      run:
        working-directory: webapp

    timeout-minutes: 10
    # We're running on ubuntu-latest, nothing special
    runs-on: ubuntu-latest
    steps:
      # As usual, we simply checkout the project
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 8.2.0

      - name: Install dependencies
        run: pnpm install

      - name: Build the project
        run: pnpm run build

      - name: Run lints
        run: pnpm run lint

      - name: Run checks
        run: pnpm run check

      - name: Run tests
        run: pnpm run test:unit
      
      - name: debug
        run: ls -la

      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: webapp
          path: build

  deploy-webapp:
    needs: test-webapp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: webapp
      - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "the-hidden-threat"
          heroku_email: "mmo@foryouandyourcustomers.com"